### without numpy doing maths(matrix maths) is very complex in any language

In [1]:
import numpy as np

In [5]:
x=np.array([
    [1,2,3],
    [3,4,5]
])
print(x)
print(type(x))
print(x.shape)
print(x.sum())

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)
18


In [6]:
print(x.sum())
print(x.sum(axis=0)) #sum of each column
print(x.sum(axis=1))  # sum of each row

18
[4 6 8]
[ 6 12]


In [8]:
a=np.array([1,2,3]) # 1d array
b=np.array([[1,2],[3,4],[4,5]]) # 2d array
c=np.array([[[2,3,4],[1,5,6],[8,9,0]]]) # 3d array
print(a.shape,a.ndim)
print(b.shape,b.ndim)
print(c.shape,c.ndim)

(3,) 1
(3, 2) 2
(1, 3, 3) 3


# Matrix creation
- sequential
  - arange
  - linspace
- Rnadom
  - rand
  - randint
  - uniform  

In [14]:
x=np.arange(10)
print(x)
x1=np.arange(1,11,.5)  # start,end,step  #(1,11,1.005)
x1

[0 1 2 3 4 5 6 7 8 9]


array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [16]:
y=np.linspace(1,11,5)
y

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [19]:
np.arange(1,11,.5).reshape(5,4)     #(4,5) # reshape to 4X5 matrix #reshape(5,2,2)

array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])

In [23]:
np.arange(1,11,.5).reshape(5,4)

array([[ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5]])

In [24]:
x1=np.array([[1,2,3],[4,5,6]])
x2=np.array([[4,2,3],[2,6,6]])

print(x1)
print(x2)
print(x1+x2)
print(x1-x2)
print(x1*x2)
print(x1/x2)
print(x1//x2)
print(x1%x2)
print(x1**x2)
#comparison in numpy results in boolean array
print(x1<x2)
print(x1>x2)
print(x1>=x2)
print(x1<=x2)
print(x1==x2)

[[1 2 3]
 [4 5 6]]
[[4 2 3]
 [2 6 6]]
[[ 5  4  6]
 [ 6 11 12]]
[[-3  0  0]
 [ 2 -1  0]]
[[ 4  4  9]
 [ 8 30 36]]
[[0.25       1.         1.        ]
 [2.         0.83333333 1.        ]]
[[0 1 1]
 [2 0 1]]
[[1 0 0]
 [0 5 0]]
[[    1     4    27]
 [   16 15625 46656]]
[[ True False False]
 [False  True False]]
[[False False False]
 [ True False False]]
[[False  True  True]
 [ True False  True]]
[[ True  True  True]
 [False  True  True]]
[[False  True  True]
 [False False  True]]


In [25]:
a=np.random.rand(3,2)
a

array([[0.12968592, 0.86853196],
       [0.52385307, 0.71811537],
       [0.94064041, 0.70796977]])

In [26]:
np.set_printoptions(precision=2)


In [28]:
b=np.random.randint(0,10,(3,3))
b

array([[1, 7, 6],
       [4, 0, 6],
       [7, 5, 8]])

In [29]:
c=np.random.uniform(0,10,(3,3))
c

array([[7.97, 3.27, 3.89],
       [9.27, 9.37, 6.84],
       [9.75, 4.82, 7.97]])